name: CI Linux

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: dialog
          submodules: true
      - name: Setup V
        run: |
          curl -Lo v_linux.zip https://github.com/vlang/v/releases/latest/download/v_linux.zip
          unzip -o v_linux.zip
          mv v ~/v
      - name: Setup dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev
          version: 1.0
      - name: Setup V module
        run: mkdir ~/.vmodules && mv dialog ~/.vmodules/dialog
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [tcc, gcc, clang]
        optimization: ['', '-W -cstrict']
        exclude:
          - cc: tcc
            optimization: '-W -cstrict'
      fail-fast: false
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }} ${{ matrix.optimization }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Setup dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev
          version: 1.0
      - name: Build examples
        run: v ~/.vmodules/dialog/examples/minimal.v
