name: CI macOS

on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dialog
          submodules: true
      - name: Setup V
        run: |
          curl -Lo v_macos_arm64.zip https://github.com/vlang/v/releases/latest/download/v_macos_arm64.zip
          unzip -o v_macos_arm64.zip
          mv v ~/v && ~/v/v symlink
      - name: Setup dependencies
        run: |
          v install https://github.com/ttytm/webview
          ~/.vmodules/webview/build.vsh --silent
      - name: Setup V module
        run: mv dialog ~/.vmodules/dialog
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  test:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        cc: [clang]
        # cc: [tcc, clang]
        # optimization: ['', '-W -cstrict']
        # exclude:
        #   - cc: tcc
        #     optimization: '-W -cstrict'
      fail-fast: false
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }} ${{ matrix.optimization }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Build examples
        run: v ~/.vmodules/dialog/examples/minimal.v
