name: CI Windows

on:
  workflow_call:

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dialog
          submodules: true
      - name: Setup V
        shell: bash
        run: |
          curl -Lo v_windows.zip https://github.com/vlang/v/releases/latest/download/v_windows.zip
          7z x v_windows.zip
          mv v ~/v
      - name: Setup V module
        run: bash -c "mkdir -p ~/.vmodules && mv dialog ~/.vmodules/dialog"
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  test:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        cc: [gcc] # [tcc, gcc, msvc]
        optimization: ['', '-W -cstrict']
        # exclude:
        #   - cc: tcc
        #     optimization: '-W -cstrict'
      fail-fast: false
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: |
          ~/v/v symlink
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          v -showcc self && v doctor
      - name: Build examples
        run: v $HOME/.vmodules/dialog/examples/minimal.v
